name: 'parent updates'

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'hwany7seo/test_action'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'autopr'
    steps:
    - uses: actions/checkout@v3
    - name: get last commit message
      shell: bash
      run: |
      MSG=$(git log -1 --format=%s)
    
    - name: run action
      id: run_action
      uses: ./
      with: 
        github_token: ${{ secrets.TOKEN }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
        owner: ${{ env.OWNER }}
        label : ${{MSG}
