name: 'parent updates'

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'hwany7seo/test_action'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'hwany7seo'
      COMMIT_MSG: Update Submodule
      PR_BODY: PR BODY
    steps:
    - uses: actions/checkout@v2
    - name: get last commit message
      shell: bash
      run: |
        COMMIT_MESSAGE=$(echo $(git log -1 --format=%s))
        echo "::set-output name=commit-message::${COMMIT_MESSAGE}"
        echo "commitmsg=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
        echo "COMMIT_MSG=$(echo $(git log -1 --format=%s))" >> $GITHUB_ENV
      id: getcommitmsg
    - name: Checkout parent repository and branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ env.PARENT_REPOSITORY }}
        ref: ${{ env.CHECKOUT_BRANCH }}
        submodules: true
        fetch-depth: 0
    - name: Create new branch and push changes
      shell: bash
      run: |
        echo $(git log -1 --format=%s)
        echo "$(git log -1 --format=%s)"
        echo "aaaaaaaa"
        echo ${{ steps.getcommitmsg.outputs.commitmsg }}
        echo ${{ steps.getcommitmsg.outputs.commit-message }}
        echo ${{ env.COMMIT_MSG }}
