name: 'parent updates'

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'hwany7seo/test_action'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'hwany7seo'
      COMMIT_MSG: Update Submodule
      PR_BODY: PR BODY
    steps:
    - uses: actions/checkout@v2
    - name: get last commit message
      shell: bash
      run: |
        COMMIT_MESSAGE=$(echo $(git log -1 --format=%s))
        echo "commitmsg=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
        echo "commit-message=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
        echo "COMMIT_MSG=$(echo $(git log -1 --format=%s))" >> $GITHUB_ENV
      id: getcommitmsg
    - name: Checkout parent repository and branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ env.PARENT_REPOSITORY }}
        ref: ${{ env.CHECKOUT_BRANCH }}
        submodules: true
        fetch-depth: 0
    - name: Create new branch and push changes
      shell: bash
      run: |
        git config user.name cubrid
        git config user.email github-actions@github.com
        git submodule update --remote
        git checkout -b $GITHUB_RUN_ID
        git commit -am "'${{ github.event.head_commit.message }}'"
        git push --set-upstream origin $GITHUB_RUN_ID   
    - name: value check
      shell: bash
      run: |
        echo $(git log -1 --format=%s)
        echo "$(git log -1 --format=%s)"
        echo "aaaaaaaaaaaa"
        echo ${{ steps.getcommitmsg.outputs.commitmsg }}
        echo ${{ steps.getcommitmsg.outputs.commit-message }}
        echo ${{ github.event.head_commit.message }}
        echo ${{ toJSON(github.event.head_commit.message) }}
        echo ${{ process.env.GITHUB_RUN_ID }}

