name: 'parent updates'

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'hwany7seo/test_action'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'autopr'
      LABEL: Update Submodule
    steps:
    - uses: actions/checkout@v2
    - name: get last commit message
      shell: bash
      run: |
        echo "{msg}=$(git log -1 --format=%s)" >> $GITHUB_OUTPUT
      id: getcommitmsg
    - name: run action
      id: run_action
      uses: ./
      with: 
        github_token: ${{ secrets.TOKEN }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
        owner: ${{ env.OWNER }}
        label: ${{ steps.getcommitmsg.outputs.msg }}
